find_package(Vulkan 1.3 REQUIRED)
if (WIN32)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DVK_USE_PLATFORM_WIN32_KHR")
elseif (UNIX)

elseif (APPLE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DVK_USE_PLATFORM_MACOS_MVK -DVK_EXAMPLE_XCODE_GENERATED")
else ()
    message(FATAL "Unsupported platform")
endif ()

if (DEFINED ENV{VULKAN_SDK})
    message(STATUS "Found Vulkan SDK: $ENV{VULKAN_SDK}")
else ()
    message(FATAL_ERROR "VULKAN_SDK is not set. Please install Vulkan SDK from here: https://vulkan.lunarg.com/")
endif ()