IF(WIN32)
    IF (NOT Vulkan_FOUND)
        if(DEFINED ENV{VK_SDK_PATH})
            find_library(Vulkan_LIBRARY NAMES vulkan-1 vulkan PATHS $ENV{VK_SDK_PATH}/Lib)
            IF (Vulkan_LIBRARY)
                set(Vulkan_FOUND ON)
                include_directories($ENV{VK_SDK_PATH}/Include)
                MESSAGE("Using Vulkan SDK installed here:" $ENV{VK_SDK_PATH})
            ENDIF()
        ELSE()
            MESSAGE(FATAL_ERROR "Vulkan not found. Make sure you have Vulkan SDK installed in your system")
        ENDIF()
    ELSE()
        include_directories(${Vulkan_INCLUDE_DIR})
    ENDIF()
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DVK_USE_PLATFORM_WIN32_KHR")
ELSEIF(UNIX)
    find_package(vulkan)
    IF (NOT Vulkan_FOUND)
        find_library(Vulkan_LIBRARY NAMES vulkan HINTS $ENV{VULKAN_SDK}/lib REQUIRED)
        IF (Vulkan_LIBRARY)
            set(Vulkan_FOUND ON)
	    include_directories($ENV{VULKAN_SDK}/include)
            MESSAGE("Using bundled Vulkan library version")
        ENDIF()
    ENDIF()
    find_package(Threads REQUIRED)
ELSEIF(APPLE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DVK_USE_PLATFORM_MACOS_MVK -DVK_EXAMPLE_XCODE_GENERATED")
    # Todo : android?
ENDIF(WIN32)

IF (NOT Vulkan_FOUND)
    message(FATAL_ERROR "Could not find Vulkan library!")
ELSE()
    message(STATUS ${Vulkan_LIBRARY})
ENDIF()
